### ISSUE TITLE
EasyTime: default_language setting breaks clock_phrase 12 hour format in Dutch?

### ISSUE THREAD

**Issue by kixtarter** [Petro31/easy-time-jinja#63]
First of all: thanks again for your wonderful jinja script!
It is very useful for speaking the time with Home Assistant TTS in my native language.

I just discovered the `default_language` option in the `easy_time.jinja` script, so I did set it to `‘nl’` for my Dutch language, and then I removed all the individual `language='nl'` entries from my automations.
However, it looks like this breaks the way the script handles the 12 hour format.

This is what I got before modifying the default_language:

```
In the easy_time.jinja file:

{%- set default_language = 'en' %}

In the automation:

{% from 'easy_time.jinja' import clock_phrase %}
{{ clock_phrase( "2025-02-19 14:10:00", language='nl' ) }}

Result:

10 over 2
```

And this is what I get now, with `default_language = ‘nl’`

```
In the easy_time.jinja file:

{%- set default_language = 'nl' %}

In the automation:

{% from 'easy_time.jinja' import clock_phrase %}
{{ clock_phrase( "2025-02-19 14:10:00" ) }}

Result:

10 over 14
```

This `14` should still be `2` doesn’t it?

**Comment by Petro31** [comment]
That's not how you modify the default language.  You set the language in the first line of the easy_time file.

**Comment by kixtarter** [comment]
Sorry that I wasn’t clear on this, but that is what I did: I did change the `default_language` value in the `easy_time.jinja` file, and not in my own yaml code.

**Comment by Petro31** [comment]
Are you running the latest version?

**Comment by kixtarter** [comment]
Yes, I think so: it is version 2.1.2

**Comment by Petro31** [comment]
fixed in latest

**Comment by kixtarter** [comment]
Thanks again for the time you did put into this Petro, but unfortunately the problem is not yet solved for me in version 2.1.3.
I did again set the default language in easy_time.jinja, and to be sure I did restart Home Assistant, but the results are the same:

```
In the easy_time.jinja file:
{%- set default_language = 'nl' %}

In the automation:
{% from 'easy_time.jinja' import clock_phrase %}
{{ clock_phrase( "2025-04-02 14:10:00" ) }}
{{ clock_phrase( "2025-04-02 14:10:00", language='en' ) }}
{{ clock_phrase( "2025-04-02 14:10:00", language='nl' ) }}


Result:
10 over 14
10 past 2
10 over 14
```

Do you see different results?
Am I missing something?

**Comment by datenzar** [comment]
Hi @kixtarter,

I experienced the same issue when maintaining German language. The problem is, that while we use a 24-hour system for time in general, the spoken phrases (`clock_phrase`) use only 12 hours. I don't know about other languages, but I would say that this system applies to Western European languages broadly.

A solution to this issue could be another parameter for each language (similar to `use_twelve`) which controls for 12/24h logic in the `clock_phrase` macro.

**Comment by kixtarter** [comment]
Hi @datenzar thanks for the confirmation.

For now I am using the `language='nl'` setting everywhere where I am using the EasyTime script (which is a lot).
This works, and I really enjoy using this great script :-)
But it would be nice if we could use the `default_language` setting instead.

Hopefully @Petro31 can find some time to look into this again.
I don’t think I can re-open this issue #63 myself, can I? Or should I create a new issue for this?

**Comment by datenzar** [comment]
Hi @kixtarter,
feel free to check out my fork in above PR as it in corporates also the Dutch translation.

**Comment by kixtarter** [comment]
Hi @datenzar, thank you!
Your modification indeed solves the problem in the Dutch language.
This are some tests I did with your modified script (#69 version 6c4d1fd):


```

# In the modified easy_time.jinja file:
{%- set default_language = 'nl' %}

# In a template:
{% from 'easy_time.jinja' import clock_phrase %}
{{ clock_phrase( "2025-04-02 14:10:00" ) }}
{{ clock_phrase( "2025-04-02 14:10:00", language='en' ) }}
{{ clock_phrase( "2025-04-02 14:10:00", language='nl' ) }}


# Result:
10 over 2
10 past 2
10 over 2
```


@Petro31: just to be sure some more background info: I am not sure if this matters, but although my native language is Dutch, I am using the English language in the Home Assistant GUI.
But I am using the 24 hours time format in the GUI, and I am using the Dutch language for all TTS messages coming from Home Assistant.
Could this set-up also be related to this issue?
